---
title: "Liver fibrosis"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(stringi)

library(rnaturalearth)

library(viridis)

library(ggh4x)

library(ggtext)
library(scales)

library(patchwork)
library(sf)

library(ggrepel)

library(broom)

library(pheatmap)
library(ComplexHeatmap)

library(mapdata)
library(ggplotify)
```

```{r}
p_name <- list.files("../plot", pattern = "RDS") %>% str_remove("\\.RDS")

p_name 
```

```{r}
p_path <- paste0("../plot/", p_name, ".RDS")

p_path
```

```{r}
for (i in 1:length(p_name )){
  assign(p_name[i], readRDS(p_path[i]))
}
```

```{r}
p1_e <- p1_e1 + p1_e2 + p1_e3 + p1_e4+ p1_e5 + p1_e6 +   p1_e7 + p1_e8+ p1_e9 +
  plot_layout(design = "
  ABCDE
  FGHI#")+
  plot_layout(axis_titles = "collect")

p1_e
```


```{r}
# assemble plot

p1 <- p1_a1 + p1_a2 +
  p1_b + patchwork::free(p1_c) + 
  patchwork::free(p1_d) + 
   patchwork::free(p1_e, type = "label") +
  plot_layout(design = "
              AABB
              AABB
              AABB
              CCDD
              CCDD
              CCDD
              EEEE
              EEEE
              EEEE
              EEEE
              EEEE
              FFFF
              FFFF
              FFFF
              FFFF")
  
  p1 
```

```{r}
ggsave("../figure/Fig1.pdf", p1,
       width = 180, height = 235, units = "mm")
```

