---
title: "Liver fibrosis"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

library(readxl)
library(openxlsx)

library(fpp3)

library(scales)
library(glue)
library(ggtext)

library(cowplot)

library(patchwork)

```


```{r}
# make df folder

#dir.create("../df/long", showWarnings = TRUE, recursive = FALSE, #mode = "0777")
```

```{r}
df_test_dem_reg <- readRDS("../rds/test/dem/df_test_dem_reg")

df_test_prf_reg <-  readRDS("../rds/test/prf/df_test_prf_reg")
```

```{r}
df_img_dem_add <- readRDS("../rds/img/dem/df_img_dem_add")

df_img_prf_add <- readRDS("../rds/img/prf/df_img_prf_add")
```




```{r}
df_test_dem <- df_test_dem_reg %>%
  bind_rows(df_img_dem_add) %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(TOTAL = str_replace(TOTAL, "-", "0")) %>%
  mutate(TOTAL = as.numeric(TOTAL))
  
```

```{r}
df_test_prf <- df_test_prf_reg %>%
  bind_rows(df_img_prf_add) %>%
  rename(YEAR = "YEAR_str") %>%
    mutate(TOTAL = str_replace(TOTAL, "-", "0")) %>%
  mutate(TOTAL = as.numeric(TOTAL))
```

```{r}
# 160029310	 P-3-P 	
# 160125050 ４型コラーゲン・７Ｓ 
# 160145310	４型コラーゲン
# 160151150 ヒアルロン酸
# 160204950 M2BPGi
# 160215150 オートタキシン 
# 160189750 TE
# 160207310 USE
# 160231410 CAP
# 170040170 MRE

df_fib_marker <- tibble(PRO_code = c("160029310",
                                     "160125050",
                                     "160145310",
                                     "160151150",
                                     "160204950",
                                     "160215150",
                                     "160189750",
                                     "160207310",
                                     "160231410",
                                     "170040170"),
                        FIB = c("P-3-P",
                                "COL4-7S",
                                "COL4",
                                "HA",
                                "M2BPGi",
                                "Autotaxin",
                                "TE",
                                "USE",
                                "CAP",
                                "MRE")) 
```


```{r}
levels_fib <- c("P-3-P",
                                "COL4-7S",
                                "COL4",
                                "HA",
                                "M2BPGi",
                                "Autotaxin",
                                "TE",
                                "USE",
                                "CAP",
                                "MRE")
```

```{r}
df_fib_marker <- df_fib_marker %>%
  mutate(FIB = factor(FIB, levels = levels_fib))
```

```{r}
df_fib_dem <- df_test_dem %>%
  filter(PRO_code %in% df_fib_marker$PRO_code) %>%
  left_join(df_fib_marker,
            by = join_by(PRO_code))
```

```{r}
df_fib_dem %>%
  distinct(CLASS_code, PRO_code, PRO_name)
```

```{r}
df_fib_prf <- df_test_prf %>%
  filter(PRO_code %in% df_fib_marker$PRO_code) %>%
  left_join(df_fib_marker,
            by = join_by(PRO_code))
```

# convert to long

```{r}
df_fib_prf_long <- df_fib_prf  %>%
  pivot_longer(col = c(ends_with("都"),
                       ends_with("道"),
                       ends_with("府"),
                       ends_with("県")),
               names_to = "PRF_jp",
               values_to = "VALUE")
```

# format prf

```{r}
df_prf <- rnaturalearth::ne_states("japan") %>% 
  as_tibble() %>%
  select(iso_3166_2, name_ja, name_en) %>%
  rename(PRF_jp = "name_ja",
         PRF= "name_en") %>%
  arrange(iso_3166_2)
```

```{r}
df_prf <- df_prf %>%
  mutate(PRF = str_remove(PRF, "Prefecture")) %>%
  mutate(PRF = str_trim(PRF, side = "both")) %>%
  mutate(PRF = str_replace_all(PRF, "Ō", "O")) %>%
  mutate(PRF = str_replace_all(PRF, "ō", "o"))
```

```{r}
df_fib_prf_long <- df_fib_prf_long %>%
  left_join(df_prf,
            by = join_by(PRF_jp))
```

```{r}
prf_levels <- df_fib_prf_long %>%
  distinct(iso_3166_2, PRF) %>%
  arrange(iso_3166_2) %>%
  pull(PRF)

prf_levels 
```

```{r}
df_fib_prf_long <- df_fib_prf_long %>%
  mutate(PRF = factor(PRF, levels = prf_levels))
```

```{r}
df_fib_prf_long <- df_fib_prf_long %>%
  mutate(VALUE = str_replace(VALUE, "-", "0")) %>%
  mutate(VALUE = as.numeric(VALUE))
```

```{r}
df_fib_prf_total <- df_fib_prf_long %>%
  distinct(YEAR, SHEET, PRO_code, .keep_all = TRUE) %>%
  group_by(YEAR, FIB) %>%
  summarise(SUM_total = sum(TOTAL)) %>%
  ungroup()

df_fib_prf_total
```

```{r}
df_fib_prf_value <- df_fib_prf_long %>%
  group_by(YEAR, FIB) %>%
  summarise(SUM_value = sum(VALUE)) %>%
  ungroup()

df_fib_prf_value
```


```{r}
df_fib_prf_dif <- df_fib_prf_total %>%
  mutate(ID = paste0(FIB, "_", YEAR)) %>%
  left_join(df_fib_prf_value %>%
              mutate(ID = paste0(FIB, "_", YEAR)) %>%
              select(ID, SUM_value),
            by = join_by(ID)) %>%
  select(! ID)

df_fib_prf_dif
```


```{r}
df_fib_prf_dif <- df_fib_prf_dif %>%
   mutate(DIF = (SUM_value - SUM_total) / SUM_total * 100)

df_fib_prf_dif 
```

```{r}
df_fib_prf_dif_lab <- df_fib_prf_dif %>%
  mutate(across(starts_with("SUM"), ~ scales::comma(.x) ))

df_fib_prf_dif_lab
```

```{r}
df_fib_prf_dif_2023 <- df_fib_prf_dif_lab %>%
  filter(YEAR == "2023") 

df_fib_prf_dif_2023
```

```{r}
df_fib_prf_dif_2023 <- df_fib_prf_dif_2023 %>%
  mutate(DIF = round(DIF, digits = 2)) %>%
  mutate(DIF = format(DIF, nsmall = 2)) %>%
  mutate(DIF = str_remove_all(DIF, "\\s")) %>%
  mutate(DIF = str_replace(DIF, "0\\.00", "0")) 

df_fib_prf_dif_2023 
```


```{r}
# df_fib_prf_dif_2023 %>%
#  rename(Year = "YEAR",
#         Test = "FIB") %>%
#  write.xlsx("../table/TableS8.xlsx")
```


```{r}
df_fib_prf_dif_lab
```


```{r}
df_fib_prf_dif_lab %>%
  filter(YEAR == "2023") %>%
  select(YEAR, FIB, starts_with("SUM_"), DIF) %>%
  mutate(DIF = formatC(DIF, digits = 2, format = "fg", flag = "#")) %>%
  mutate(DIF = str_replace_all(DIF, "-", "−")) %>%
  rename(Year = "YEAR",
         Test = "FIB",
         Total_claim_n_1 = "SUM_total",
         Total_claim_n_2 = "SUM_value",
         Difference_from_national_data = "DIF") %>%
  write.xlsx("../table/TableS6.xlsx")
```


```{r}
df_fib_prf_dif_lab %>%
  select(YEAR, FIB, DIF) %>%
  mutate(DIF = str_remove_all(DIF, "\\s")) %>%
  pivot_wider(names_from = FIB,
              values_from = DIF,
              values_fill = "-") 
```


```{r}
df_fib_prf_dif_lab %>%
  select(YEAR, FIB, DIF) %>%
  mutate(DIF = formatC(DIF, digits = 2, format = "fg")) %>%
  mutate(DIF = str_remove_all(DIF, "\\s")) %>%
  mutate(DIF = case_when(str_detect(DIF, "^\\-[1-9]$")|
                           str_detect(DIF, "^\\-0.[1-9]$") |
                          str_detect(DIF, "^\\-0.0[1-9]$") ~ paste0(DIF, "0"),
                          .default = DIF) ) %>%
  pivot_wider(names_from = FIB,
              values_from = DIF,
              values_fill = "-") %>%
  rename(Year = "YEAR") %>%
  select(any_of(c("Year",
                  levels_fib))) #%>%
#  write.xlsx("../table/TableS6.xlsx")
```

